spring:
  application:
    name: mofumo
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 300 # 5 days
    refreshTokenExpiration: 604800 # 7 days
